name: flutter_wallet_ui_challenge
description: A new Flutter project for RedotPay Clone.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # هذا السطر هو الذي سيحل مشكلة الفشل في الصورة 1000049021

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6 # تحديث الأيقونات لضمان التوافق مع Dart 3 
