name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0' # استخدام النسخة الأكثر استقراراً لمشروعك

      - name: Get dependencies
        run: flutter pub get

      - name: Clean build files
        run: flutter clean # مسح الملفات القديمة التي سببت أخطاء Groovy

      - name: Build APK
        run: flutter build apk --debug --ignore-deprecation # تجاوز تحذيرات النسخة القديمة

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Fuel-Station-App
          path: build/app/outputs/flutter-apk/app-debug.apk
